from schemas.relative.base import GenericResponseSchema as GenericResponseSchema
from schemas.relative.mtt_location_close import MttLocationCloseMttId as MttLocationCloseMttId
from schemas.relative.mtt_location_close import MttLocationCloseDistance as MttLocationCloseDistance
from schemas.relative.mtt_location_close import MttLocationCloseMtt as MttLocationCloseMtt
from schemas.relative.parent_kid_application import ParentKidApplicationInDB as ParentKidApplicationInDB
from schemas.relative.parent_kid_application import ParentKidApplicationStatus as ParentKidApplicationStatus
from schemas.relative.parent_fees_kid_foods import ParentFeesKidFoods as ParentFeesKidFoods
from schemas.relative.parent_fees_kid_payment import ParentFeesKidPay as ParentFeesKidPay
from schemas.relative.parent_fees_kid_visit_data import ParentFeesKidVisitData as ParentFeesKidVisitData
from schemas.relative.parent_fees_mtt_data import ParentFeesMttDataSchema as ParentFeesMttDataSchema
from schemas.relative.parent_fees_mtt_statistics import ParentFeesMttStatistics as ParentFeesMttStatistics
from schemas.relative.parent_kid_search import ParentKidSearch as ParentKidSearch
from schemas.relative.mtt_location_close import RegionSchemas, MttPhotosSchema
from schemas.relative.parent_kid_application import ParentSdkAuthResponse,RealPaySchema